rootAction:
  key: search_and_filter::form.toggle_type_0
  conditionActions:
    falseAction:
      key: search_and_filter::form.toggle_type_2
      action:
        key: x8587hf0
    trueActions:
      - condition:
          variable:
            defaultValue:
              serializedValue: form.selected_types.contains(Documents)
        trueAction:
          key: search_and_filter::form.toggle_type_1
          action:
            key: z3jhnftx
trigger:
  triggerType: ON_TAP